#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    # 使用阿里巴巴的开源框架druid数据库连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    platform: mysql
#    # mysql 8.0.+使用的驱动
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: f
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#
#mybatis:
#  # mapper映射文件地址，这里我在src/main/resouces下新建文件夹mapper
#  mapper-locations: classpath*:mapper/*.xml
#  # 配置bean扫描目录，也可用注解
#  type-aliases-package: classpath*:com.springboot.springinit.entity

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000           #连接超时时间
    jedis:
      pool:
        max-wait: 30000     #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 100     #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20        #连接池中的最大空闲连接
        min-idle: 0         #连接池中的最小空闲连接

  rabbitmq:                  #配置rabbitMq 服务器
    host: 192.168.203.128
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以设置,前提是在rabbitmq服务上创建了自己的虚拟host
    #virtual-host: JCcccHost